[colors]
ansi = [
    '#5C6577',
    '#e06c75',
    '#98c379',
    '#e5c07b',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#dcdfe4',
]
background = '#282c34'
brights = [
    '#5C6577',
    '#e06c75',
    '#98c379',
    '#e5c07b',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#dcdfe4',
]
cursor_bg = '#a3b3cc'
cursor_border = '#a3b3cc'
cursor_fg = '#dcdfe4'
foreground = '#dcdfe4'
selection_bg = '#474e5d'
selection_fg = '#dcdfe4'

[colors.indexed]

[metadata]
name = 'okmanideep'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
