if &compatible
    set nocompatible
end

call plug#begin('~/.vim/plugged')

"Autocomplete"
Plug 'neoclide/coc.nvim', {'branch': 'release'}
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes
"Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()
" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gf <Plug>(coc-references)
nmap <silent> rr <Plug>(coc-rename)
nmap <leader>g[ <Plug>(coc-diagnostic-prev)
nmap <leader>g] <Plug>(coc-diagnostic-next)
nmap <silent> <leader>gp <Plug>(coc-diagnostic-prev-error)
nmap <silent> <leader>gn <Plug>(coc-diagnostic-next-error)
nnoremap <leader>cr :CocRestart


Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
nnoremap <C-p> :Files<CR>

"color schemes"
Plug 'gruvbox-community/gruvbox'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16-vim'
Plug 'hzchirs/vim-material'
Plug 'w0ng/vim-hybrid'

Plug 'sheerun/vim-polyglot'

Plug 'itchyny/lightline.vim'
let g:lightline={'colorscheme':'seoul256'}

"toggle comments"
Plug 'preservim/nerdcommenter'

Plug 'godlygeek/tabular'

"Auto closing brackets and quotes"
Plug 'Raimondi/delimitMate'

Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'

Plug 'vimwiki/vimwiki'
let g:vimwiki_list = [{'path': '~/Dropbox/notes', 'syntax': 'markdown', 'ext': '.md'}]
let g:vimwiki_key_mappings = {'lists': 0}

Plug 'mxw/vim-jsx'

Plug 'neomake/neomake'

call plug#end()

syntax on
set hidden "Moving out of the file hides it and doesn't close
set noerrorbells

colorscheme gruvbox
let g:gruvbox_contrast_dark='hard'
set background=dark

set number
set relativenumber
set tabstop=2
set expandtab
set shiftwidth=4
set smartindent
set nowrap
set smartcase
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

"dont highlight search results
set nohlsearch

"highlight search results as you type
set incsearch

"Display whitespace characters
set encoding=utf-8
set magic
set listchars=tab:│\ ,trail:·
set list

set noswapfile
set nobackup
set nowritebackup
set undodir=~/.vim/undodir
set undofile

:noremap <Up> <NOP>
:noremap <Down> <NOP>
:noremap <Left> <NOP>
:noremap <Right> <NOP>

"nvim terminal esc
if(has("nvim"))
    :tnoremap <Esc> <C-\><C-n>
endif

if executable('rg')
    let g:rg_derive_root='true'
endif

"Faster movements
nmap J 5j
nmap K 5k
vmap J 5j
vmap K 5k
nmap T <C-u>
nmap B <C-d>

"Switch splits faster
:nnoremap <C-h> <C-w>h
:nnoremap <C-j> <C-w>j
:nnoremap <C-k> <C-w>k
:nnoremap <C-l> <C-w>l
if(has("nvim")) 
    :tnoremap <C-h> <C-\><C-n><C-w>h
    :tnoremap <C-j> <C-\><C-n><C-w>j
    :tnoremap <C-k> <C-\><C-n><C-w>k
    :tnoremap <C-l> <C-\><C-n><C-w>l
endif

"go to cmd mode more easily
nnoremap ; :

"change leader from \ to space
let mapleader = " "

"quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

"turn on spell check locally
nmap <silent> <leader>sp :setlocal spell<CR>
nmap <silent> <leader>ns :setlocal nospell<CR>

"clears the search highlights
nmap <silent> <leader>/ :nohlsearch<CR>

nnoremap <silent> - :Ex<CR>
let g:netrw_banner=0
let g:netrw_winsize=25

"alternative for `;` since `;` is mapped to `:`
"this line needs to be after changing the leader from \
nnoremap \ ;

:vmap <leader>y "+y
:nmap <leader>p "+p

nmap <leader>x <Plug>VimwikiToggleListItem

function! StrikeOff() 
    normal ys$<del>
endfunction

" overriding bad mappings by plugins
nmap <C-\>1 <Plug>VimwikiRemoveHeaderLevel
nmap <C-\>2 <Plug>VimwikiAddHeaderLevel
nmap <C-\>3 <Plug>VimwikiNormalizeLink
nmap <C-\>4 <Plug>VimwikiListNextSymbol
nmap <C-\>5 <Plug>VimwikiListPrevSymbol
nmap <C-\>6 <Plug>VimwikiListToggle
imap <C-\>7 <Plug>VimwikiReturn

nnoremap <leader>d :call StrikeOff()<CR>

set wildignore+=*.class,*.pyc,*.iml

let g:vim_markdown_folding_disabled=1

nnoremap <leader>t :vsp <CR>:term<CR>:vert resize 40<CR>A
