if filereadable(expand("~/.vim/plugrc"))
    source ~/.vim/plugrc
endif

syntax on
set background=dark
colorscheme base16-atelierforest

filetype on
filetype plugin on

set number
set tabstop=4
set shiftwidth=4
set expandtab
filetype plugin indent on

"highlight search results
set hlsearch

"highlight search results as you type
set incsearch

"Display whitespace characters
set magic
set listchars=tab:│\ ,trail:·
set list

:noremap <Up> <NOP>
:noremap <Down> <NOP>
:noremap <Left> <NOP>
:noremap <Right> <NOP>

"Shift+enter as Esc
:inoremap <S-CR> <Esc>

"Iterm Shift+Enter hack
:inoremap ✠ <Esc>

"move up and down by visual lines
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk

"Faster movements
nmap J 5j
nmap K 5k
vmap J 5j
vmap K 5k

"Switch splits faster
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

"go to cmd mode more easily
nnoremap ; :

"change leader from \ to ,
let mapleader = ","

"page down and page up the easy way
nnoremap <leader>f <C-f>
nnoremap <leader>b <C-b>

"quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

"clears the search highlights
nmap <silent> <leader>/ :nohlsearch<CR>

"alternative for `;` since `;` is mapped to `:`
"this line needs to after changing the leader from \
nnoremap \ ;

:vmap <leader>y "+y
:nmap <leader>p "+p

set wildignore+=*.class,*.pyc,*.iml

let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1
