if &compatible
    set nocompatible
end

call plug#begin('~/.vim/plugged')

"Autocomplete"
Plug 'neoclide/coc.nvim', {'branch': 'release'}
set cmdheight=2
set updatetime=300
set shortmess+=c
set signcolumn=yes
"Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()
" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
nnoremap <C-p> :GFiles<CR>

"color schemes"
Plug 'gruvbox-community/gruvbox'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16-vim'
Plug 'w0ng/vim-hybrid'

Plug 'sheerun/vim-polyglot'
Plug 'vim-airline/vim-airline'

"toggle comments"
Plug 'scrooloose/nerdcommenter'

"Auto closing brackets and quotes"
Plug 'Raimondi/delimitMate'

"Vim Markdown"
Plug 'plasticboy/vim-markdown'

Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'

Plug 'mxw/vim-jsx'

Plug 'neomake/neomake'

call plug#end()

syntax on
set hidden "Moving out of the file hides it and doesn't close
set noerrorbells

colorscheme gruvbox
set background=dark

set number
set relativenumber
set tabstop=2
set expandtab
set shiftwidth=4
set smartindent
set nowrap
set smartcase
set colorcolumn=80
highlight ColorColumn ctermbg=0 guibg=lightgrey

"dont highlight search results
set nohlsearch

"highlight search results as you type
set incsearch

"Display whitespace characters
set encoding=utf-8
set magic
set listchars=tab:│\ ,trail:·
set list

set noswapfile
set nobackup
set nowritebackup
set undodir=~/.vim/undodir
set undofile

:noremap <Up> <NOP>
:noremap <Down> <NOP>
:noremap <Left> <NOP>
:noremap <Right> <NOP>

"nvim terminal esc
if(has("nvim"))
    :tnoremap <Esc> <C-\><C-n>
endif

if executable('rg')
    let g:rg_derive_root='true'
endif

"Faster movements
nmap J 5j
nmap K 5k
vmap J 5j
vmap K 5k
nmap T <C-u>
nmap B <C-d>

"Switch splits faster
:nnoremap <C-h> <C-w>h
:nnoremap <C-j> <C-w>j
:nnoremap <C-k> <C-w>k
:nnoremap <C-l> <C-w>l
if(has("nvim")) 
    :tnoremap <C-h> <C-\><C-n><C-w>h
    :tnoremap <C-j> <C-\><C-n><C-w>j
    :tnoremap <C-k> <C-\><C-n><C-w>k
    :tnoremap <C-l> <C-\><C-n><C-w>l
endif

"go to cmd mode more easily
nnoremap ; :

"change leader from \ to space
let mapleader = " "

"quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

"turn on spell check locally
nmap <silent> <leader>sp :setlocal spell<CR>
nmap <silent> <leader>ns :setlocal nospell<CR>

"clears the search highlights
nmap <silent> <leader>/ :nohlsearch<CR>

nnoremap <leader>f :Vex<CR>
let g:netrw_list_style=3
let g:netrw_browse_split=4
let g:netrw_banner=0
let g:netrw_winsize=25

"alternative for `;` since `;` is mapped to `:`
"this line needs to be after changing the leader from \
nnoremap \ ;

:vmap <leader>y "+y
:nmap <leader>p "+p

function! StrikeOff() 
    normal ys$<del>
endfunction

nnoremap <leader>d :call StrikeOff()<CR>

set wildignore+=*.class,*.pyc,*.iml

let g:vim_markdown_folding_disabled=1
