highlight jsThis cterm=italic gui=italic
highlight Statement cterm=italic gui=italic
highlight jsSuper cterm=italic gui=italic
highlight jsImport cterm=italic gui=italic
highlight jsFrom cterm=italic gui=italic
highlight jsClassKeyword cterm=italic gui=italic
highlight jsExtendsKeyword cterm=italic gui=italic
highlight jsStorageClass cterm=italic gui=italic
highlight jsClassMethodType cterm=italic gui=italic
