export TERM="xterm-256color"

alias desk="cd ~/Desktop"
alias logo="git log --pretty=oneline"
alias fopen="open finder ."
alias open="open -a "
alias chrome="open Google\ Chrome "
alias apache_start="sudo apachectl start"
alias apache_stop="sudo apachectl stop"
alias apache_restart="sudo apachectl restart"
alias hide="chflags hidden"
alias unhide="chflags nohidden"
export CLICOLOR=1
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

#Add user specific profile
#Those aliases which are specific for users directory tree
source ~/.bash_profile_user
