
#Add user specific profile
#Those aliases which are specific for users directory tree
source ~/.bash_profile_user

export TERM="xterm-256color"

alias desk="cd ~/Desktop"

alias zrc="vim ~/.zshrc"
alias vrc="vim ~/.vimrc"
alias vbash="vim ~/.bash_profile"
alias vbuser="vim ~/.bash_profile_user"
alias glr="git pull --rebase"

alias gds="git diff --staged"

alias apache_start="sudo apachectl start"
alias apache_stop="sudo apachectl stop"
alias apache_restart="sudo apachectl restart"

alias hide="chflags hidden"
alias unhide="chflags nohidden"
export CLICOLOR=1
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
